-- Gastos — esquema para Supabase (Postgres).
--
-- Cómo se usa: Supabase → SQL Editor → pegar todo esto → Run. Una sola vez.
--
-- Los nombres de columna son los mismos que tenían las pestañas del Sheet (anio, mes,
-- seccion…) a propósito: así la lógica de la app sigue leyendo exactamente las mismas
-- claves y no hay que tocarla ni volver a probarla.
--
-- Los id son "by default" y no "always": la migración necesita insertar los id que ya
-- existían para no perder la identidad de cada fila.

-- ---------------------------------------------------------------- tablas

create table if not exists categorias (
  id      bigint primary key generated by default as identity,
  anio    int  not null,
  seccion text not null,
  nombre  text not null,
  orden   int  not null default 0,
  unique (anio, seccion, nombre)
);

-- Montos cargados directo en la grilla (lo importado del sheet viejo y los ajustes a mano)
create table if not exists celdas (
  id        bigint primary key generated by default as identity,
  anio      int     not null,
  seccion   text    not null,
  categoria text    not null,
  mes       int     not null check (mes between 1 and 12),
  monto     numeric not null,
  unique (anio, seccion, categoria, mes)
);

-- Lo cargado por formulario: suma a la celda de su categoría y mes
create table if not exists movimientos (
  id           bigint  primary key generated by default as identity,
  anio         int     not null,
  mes          int     not null check (mes between 1 and 12),
  dia          int,
  tipo         text    not null check (tipo in ('gasto', 'ingreso')),
  seccion      text    not null,
  categoria    text    not null,
  subcategoria text    not null default '',
  descripcion  text    not null default '',
  -- Lo cargado en dólares se guarda convertido en "monto" (que es siempre pesos) y
  -- además con su importe y cotización originales.
  moneda       text    not null default 'ARS',
  monto_moneda numeric,
  cotizacion   numeric,
  monto        numeric not null,
  pagado       boolean not null default true,
  creado_en    timestamptz not null default now()
);

-- Lo que más se consulta: el año entero, y el detalle de una celda
create index if not exists movimientos_anio_mes on movimientos (anio, mes);
create index if not exists movimientos_categoria on movimientos (anio, seccion, categoria);
create index if not exists celdas_anio on celdas (anio);

create table if not exists subcategorias (
  id        bigint primary key generated by default as identity,
  seccion   text not null,
  categoria text not null,
  nombre    text not null,
  unique (seccion, categoria, nombre)
);

create table if not exists autos (
  id         bigint primary key generated by default as identity,
  marca      text not null default '',
  modelo     text not null default '',
  anio       text not null default '',
  km         text not null default '',
  dominio    text not null default '',
  motor      text not null default '',
  chasis     text not null default '',
  precio_ars numeric,
  precio_usd numeric
);

create table if not exists auto_services (
  id            bigint primary key generated by default as identity,
  auto_id       bigint not null references autos (id) on delete cascade,
  km            text not null default '',
  detalle       text not null default '',
  mes           text not null default '',
  precio_ars    numeric,
  mano_obra_ars numeric,
  total_usd     numeric,
  orden         int  not null default 0
);

create table if not exists auto_plan (
  id      bigint primary key generated by default as identity,
  auto_id bigint not null references autos (id) on delete cascade,
  item    text not null default '',
  detalle text not null default '',
  extra   text not null default '',
  orden   int  not null default 0
);

create table if not exists quinta (
  id        bigint primary key generated by default as identity,
  rubro     text not null,
  detalle   text not null default '',
  monto_usd numeric,
  orden     int  not null default 0
);

create table if not exists quinta_pendientes (
  id    bigint primary key generated by default as identity,
  zona  text not null,
  texto text not null,
  hecho boolean not null default false,
  orden int  not null default 0
);

-- ---------------------------------------------------------------- permisos
--
-- El repositorio es público, así que la clave "anon" de Supabase se ve. Eso está bien
-- siempre y cuando sola no alcance para nada: las políticas de abajo exigen haber
-- entrado con una cuenta.
--
-- IMPORTANTE, y esto va a mano en el panel: Authentication → Sign In / Providers →
-- desactivar "Allow new users to sign up". Sin eso cualquiera podría crearse una cuenta
-- y entrar. Creá tu usuario desde Authentication → Users → Add user.

do $$
declare t text;
begin
  foreach t in array array[
    'categorias', 'celdas', 'movimientos', 'subcategorias',
    'autos', 'auto_services', 'auto_plan', 'quinta', 'quinta_pendientes'
  ]
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "con cuenta" on %I', t);
    -- Una sola cuenta usa esto, así que no hace falta separar por usuario: alcanza con
    -- exigir que haya sesión.
    execute format(
      'create policy "con cuenta" on %I for all to authenticated using (true) with check (true)', t
    );
  end loop;
end $$;

-- ---------------------------------------------------------------- avisos en vivo
--
-- Lo que hace que el escritorio se entere en el momento de lo que cargaste en el
-- teléfono, en vez de tener que preguntar cada tanto.

alter publication supabase_realtime add table movimientos;
alter publication supabase_realtime add table celdas;
alter publication supabase_realtime add table categorias;
alter publication supabase_realtime add table subcategorias;
